### ISSUE TITLE
Compilation error with Process injection native and native-map_view_section.cpp

### ISSUE THREAD

**Issue by bestrocker221** [klezVirus/inceptor#41] opened 2022-06-13 06:47 UTC
**Describe the bug**
Compilation error when using native-map_view_section.cpp with native executable

The error is the following:
` [-] Error: C:\PATH\inceptor\temp\tmpp_gn47jr.cpp(128,32): error: non-constant-expression cannot be narrowed from type 'SIZE_T' (aka 'unsigned long long') to 'DWORD' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]`

**To Reproduce**
 python3.exe .\inceptor.py native -P -P0 process 
 
Tried to add the `-Wnoc++11-narrowing` option but still no luck.

Thanks in advance

**Comment by klezVirus** [comment] 2022-06-13 07:53
Hi @bestrocker221, based on the error I guesses this was for Clang/LLVM. 

Fixed with last commit at main branch [89cdee799e94f4dc8b8244a61fa47f6fff4206f5](https://github.com/klezVirus/inceptor/commit/89cdee799e94f4dc8b8244a61fa47f6fff4206f5).

Unfortunately, unlike GCC, MS compilers are quite strict with types etc. Luckily, in this case, the issue is easily solved with an explitic cast.

**Closed by klezVirus** 2022-06-13 07:53 UTC
